# Generated by Django 2.2.1 on 2019-06-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Set categories.', null=True, to='posts.Category'),
        ),
    ]
